import React, { useState } from 'react'
import { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import { useQuery } from '@apollo/client'
import { Box, Toolbar, Button } from '@mui/material'

import Appbar from '../../components/Appbar'
import OrderDrawer from '../../components/OrderDrawer'

import { Order } from '../../common/types'
import { ORDERS_QUERY } from '../../query/OrdersQuery'
import { isRecentOrder } from '../../common/utils'
import OrderByStoreList from '../../components/OrderByStoreList'

const OrdersPage: NextPage = () => {
  const [mobileOpen, setMobileOpen] = useState(false)
  const handleDrawerToggle = () => {
    setMobileOpen(!mobileOpen)
  }

  const { loading, error, data } = useQuery(ORDERS_QUERY, {
    notifyOnNetworkStatusChange: true,
  })
  const { orders } = data || {}

  return (
    <Box sx={{ display: 'flex' }}>
      <Head>
        <title>Namhae Life App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Appbar
        title="Namhae Life 주문관리"
        handleDrawerToggle={handleDrawerToggle}
      />

      <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
        <Toolbar />
        <OrderByStoreList
          orders={orders?.filter((order: Order) => isRecentOrder(order))}
        />
        <Box sx={{ textAlign: 'center' }}>
          <Link href="/orders/old" passHref>
            <Button variant="text" color="primary">
              이전 주문 보기
            </Button>
          </Link>
        </Box>
      </Box>

      <OrderDrawer
        mobileOpen={mobileOpen}
        handleDrawerToggle={handleDrawerToggle}
      />
    </Box>
  )
}

export default OrdersPage
